[package]
name = "embeddings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
rust-bert = "0.21.0"

[[bin]]
name = "embeddings"
path = "../bin/embeddings.rs"
